# Generated by Django 4.2.4 on 2023-08-13 11:07

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Color', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('price', models.FloatField()),
                ('material', models.CharField(choices=[('Metal', 'Metal'), ('Plastic', 'Plastic'), ('Glass', 'Glass'), ('Other', 'Other'), ('Aluminum', 'aluminum')], default='other', max_length=10)),
                ('release_date', models.DateField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=myapp.models.upload_to)),
                ('detail', models.TextField(max_length=100)),
                ('state', models.CharField(choices=[('new', 'New'), ('old', 'Old')], default='new', max_length=10)),
                ('nb', models.IntegerField()),
                ('discount', models.BooleanField(default=False)),
                ('discount_perc', models.IntegerField(default=0)),
                ('popularity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to=myapp.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='FlashDisk',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.device')),
                ('capacity', models.IntegerField()),
            ],
            bases=('myapp.device',),
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.device')),
                ('battery', models.IntegerField()),
                ('category', models.CharField(choices=[('Ultrabook', 'Ultrabook'), ('NetBook', 'Netbook'), ('Classic', 'Classic'), ('Notebook', 'Notebook'), ('1 in 2 laptop', '1 in 2 laptop'), ('Gamer', 'Gamer'), ('Elitebook', 'Gamer'), ('Probook', 'Gamer')], default='Apple', max_length=20)),
                ('brand', models.CharField(choices=[('Dell', 'Dell'), ('Lenovo', 'Lenovo'), ('Apple', 'Apple'), ('Acer', 'Acer'), ('Hp', 'Hp'), ('Microsoft', 'Microsoft'), ('Toshiba', 'Toshiba'), ('D-tech', 'D-tech')], default='Dell', max_length=10)),
                ('os', models.TextField(max_length=100)),
                ('processor_type', models.CharField(choices=[('Intel Core i3', 'Intel Core i3'), ('Intel Core i5', 'Intel Core i5'), ('Intel Core i7', 'Intel Core i3'), ('Intel Core i9', 'Intel Core i9'), ('AMD Ryzen 3', 'AMD Ryzen 3'), ('AMD Ryzen 5', 'AMD Ryzen 5'), ('AMD Ryzen 7', 'AMD Ryzen 7'), ('AMD Ryzen 9', 'AMD Ryzen 9'), ('M1', 'M1'), ('M2', 'M2'), ('Celeron', 'Celeron')], default='Intel Core i3', max_length=20)),
                ('Processor', models.TextField()),
                ('screen_size', models.IntegerField(choices=[(11, '11 inches'), (12, '12 inches'), (13, '13 inches'), (14, '14 inches'), (15, '15 inches'), (16, '16 inches'), (17, '17 inches'), (18, '18 inches')], default=15)),
                ('screen_type', models.CharField(max_length=30)),
                ('graphic_card', models.TextField(max_length=50)),
                ('graphic_card_type', models.CharField(choices=[('intern', 'Intern'), ('extern', 'Extern')], default='intern', max_length=10)),
                ('Weight', models.FloatField()),
                ('cache_mem', models.IntegerField()),
                ('ram', models.IntegerField(choices=[(0, '0 GB'), (2, '2 GB'), (4, '4 GB'), (16, '16 GB'), (32, '32 GB'), (64, '64 GB')])),
                ('hard_disk', models.IntegerField(choices=[(0, '0 GB'), (64, '64 GB'), (128, '128 GB'), (256, '256 GB'), (512, '512 GB'), (1028, '1028 GB'), (2048, '2048 GB')], default=0)),
                ('hard_disk_type', models.CharField(choices=[('SSD', 'ssd'), ('HDD', 'hdd')], default='SSD', max_length=10)),
                ('usb', models.BooleanField(default=True)),
                ('wifi', models.BooleanField(default=True)),
                ('bluetooth', models.BooleanField(default=True)),
                ('Webcam', models.BooleanField(default=True)),
            ],
            bases=('myapp.device',),
        ),
        migrations.CreateModel(
            name='PowerBank',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.device')),
                ('capacity', models.IntegerField()),
                ('Nb', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('Amperage', models.FloatField(choices=[(1, '1A'), (1.5, '1.5 A'), (2, '2 A'), (2.5, '2.5 A'), (3, '3 A')], default='1 A')),
            ],
            bases=('myapp.device',),
        ),
        migrations.CreateModel(
            name='SmartPhone',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.device')),
                ('battery', models.IntegerField()),
                ('brand', models.TextField(choices=[('Samsung', 'Samsung'), ('Iris', 'Iris'), ('Apple', 'Apple'), ('Xiaomi', 'Xiaomi'), ('Hwawei', 'Hwawei'), ('Infinix', 'Infinix'), ('Realme', 'Realme'), ('Nokia', 'Nokia'), ('Oppo', 'Oppo'), ('Ace', 'Ace'), ('Google', 'Google'), ('Microsoft', 'Microsoft'), ('Starlight', 'Starlight')], default='Ace', max_length=10)),
                ('System', models.TextField(choices=[('Android 1.0', 'android 1.0'), ('Android 1.1', 'android 1.1'), ('Android 1.5', 'android 1.5'), ('Android 1.6', 'android 1.6'), ('Android 2.0', 'android 2.0'), ('Android 2.3', 'android 2.3'), ('Android 3.0', 'android 3.0'), ('Android 4.0', 'android 4.0'), ('Android 4.1', 'android 4.1'), ('Android 4.4', 'android 4.4'), ('Android 5.0', 'android 5.0'), ('Android 6.0', 'android 6.0'), ('Android 7.O', 'android 7.0'), ('Android 8.0', 'android 8.0'), ('Android 9.0', 'android 9.0'), ('Android 10', 'android 10'), ('Android 11', 'android 11'), ('Android 12', 'android 12'), ('Android 13', 'android 13'), ('Android 14', 'android 14'), ('IOS 1', 'IOS 1'), ('IOS 2', 'IOS 2'), ('IOS 3', 'IOS 3'), ('IOS 4', 'IOS 4'), ('IOS 5', 'IOS 5'), ('IOS 6', 'IOS 6'), ('IOS 7', 'IOS 7'), ('IOS 8', 'IOS 8'), ('IOS 9', 'IOS 9'), ('IOS 10', 'IOS 10'), ('IOS 11', 'IOS 11'), ('IOS 12', 'IOS 12'), ('IOS 13', 'IOS 13'), ('IOS 14', 'IOS 14'), ('IOS 15', 'IOS 15')])),
                ('camera', models.FloatField()),
                ('camera_info', models.TextField()),
                ('front_cam', models.FloatField()),
                ('front_cam_info', models.TextField()),
                ('Processor', models.TextField()),
                ('screen_size', models.IntegerField(choices=[(4, '4 inches'), (5, '5 inches'), (6, '6 inches'), (7, '7 inches'), (8, '8 inches')], default=15)),
                ('screen_type', models.CharField(max_length=30)),
                ('Weight', models.FloatField()),
                ('Ram', models.IntegerField(choices=[(0, '0 GB'), (1, '1 GB'), (2, '2 GB'), (4, '4 GB'), (16, '16 GB')], default=0)),
                ('hard_disk', models.IntegerField(choices=[(0, '0 GB'), (1, '1 GB'), (2, '2 GB'), (4, '4 GB'), (16, '16 GB'), (32, '32 GB'), (64, '64 GB'), (128, '128 GB'), (256, '256 GB')], default=0)),
                ('Chipset', models.TextField()),
                ('gpu', models.TextField()),
                ('usb', models.BooleanField(default=False)),
                ('sim_card', models.BooleanField(default=False)),
                ('double_sim', models.BooleanField(default=False)),
                ('sim_card_type', models.TextField(choices=[('Normal sim', 'Normal Sim'), ('Micro sim', 'Micro Sim'), ('Nano sim', 'Nano Sim')], default='Nano Sim', max_length=10)),
                ('wifi', models.BooleanField(default=False)),
                ('bluetooth', models.BooleanField(default=False)),
                ('hdmi', models.BooleanField(default=False)),
                ('mem_card', models.BooleanField(default=False)),
                ('gps', models.BooleanField(default=False)),
                ('radio', models.BooleanField(default=True)),
                ('Reseau', models.IntegerField(choices=[(2, '2G'), (3, '3G'), (4, '4G'), (5, '5G')], default=4)),
                ('wireless_charging', models.BooleanField(default=False)),
            ],
            bases=('myapp.device',),
        ),
        migrations.CreateModel(
            name='SmartWatch',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.device')),
                ('brand', models.TextField(choices=[('Samsung', 'Samsung'), ('Hoco', 'Hoco'), ('Sony', 'Sony'), ('Apple', 'Apple'), ('Xiaomi', 'Xiaomi'), ('Hwawei', 'Hwawei'), ('Haylo', 'Haylo'), ('G-tab', 'G-tab'), ('Haino teko', 'Haino teko'), ('KIESLECT', 'KIESLECT'), ('Google', 'Google')], default='other', max_length=10)),
                ('System_compatible', models.TextField(choices=[('Android', 'Android'), ('IOS', 'IOS'), ('Android , IOS', 'Android , IOS')], max_length=20)),
                ('water_resistance', models.BooleanField(default=False)),
                ('Weight', models.IntegerField()),
                ('gps', models.BooleanField(default=False)),
                ('mem_card', models.BooleanField(default=False)),
                ('ram', models.FloatField()),
                ('stockage', models.FloatField()),
                ('battery', models.IntegerField()),
                ('wirless_charging', models.BooleanField(default=False)),
                ('sms', models.BooleanField(default=False)),
                ('email', models.BooleanField(default=False)),
                ('calls', models.BooleanField(default=False)),
                ('radio', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('bluetooth', models.BooleanField(default=False)),
            ],
            bases=('myapp.device',),
        ),
        migrations.CreateModel(
            name='SoundDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.device')),
                ('brand', models.TextField(choices=[('Samsung', 'Samsung'), ('Hoco', 'Hoco'), ('Haino teko', 'Haino teko'), ('AWEI', 'AWEI'), ('Anker', 'Anker'), ('Beats', 'Beats'), ('Bose', 'Bose'), ('Sony', 'Sony'), ('Celebrat', 'Celebrat'), ('Apple', 'Apple'), ('Xiaomi', 'Xiaomi'), ('Hwawei', 'Hwawei'), ('YINDU', 'YINDU'), ('JBL', 'JBL'), ('Lenovo', 'Lenovo'), ('LG', 'LG')], default='other', max_length=10)),
                ('category', models.TextField(choices=[('Headset', 'Headset'), ('Earphone', 'Earphone'), ('Speaker', 'Speaker'), ('Earpiece', 'Earpiece'), ('Microphone', 'Microphone')], default='Speaker', max_length=10)),
                ('bluetooth', models.BooleanField(default=False)),
                ('wired', models.BooleanField(default=False)),
            ],
            bases=('myapp.device',),
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.device')),
                ('battery', models.IntegerField()),
                ('brand', models.TextField(choices=[('Samsung', 'Samsung'), ('Iris', 'Iris'), ('Apple', 'Apple'), ('C-idea', 'C-idea'), ('Hwawei', 'Hwawei'), ('Condor', 'Condor'), ('Lenovo', 'Lenovo'), ('Black View', 'Black_view'), ('D-tech', 'D-tech')], default='other', max_length=20)),
                ('System', models.TextField(choices=[('Android', 'Android'), ('IOS', 'IOS')], max_length=10)),
                ('camera', models.FloatField()),
                ('front_cam', models.FloatField()),
                ('Processor', models.TextField()),
                ('screen_size', models.IntegerField(choices=[(5, '5 inches'), (6, '6 inches'), (7, '7 inches'), (8, '8 inches'), (9, '9 inches'), (10, '10 inches'), (11, '11 inches'), (12, '12 inches')], default=15)),
                ('screen_type', models.CharField(max_length=30)),
                ('Weight', models.FloatField()),
                ('Ram', models.IntegerField(choices=[(0, '0 GB'), (1, '1 GB'), (2, '2 GB'), (4, '4 GB'), (16, '16 GB')], default=0)),
                ('hard_disk', models.IntegerField(choices=[(0, '0 GB'), (4, '4 GB'), (16, '16 GB'), (32, '32 GB'), (64, '64 GB')], default=0)),
                ('hard_disk_type', models.TextField(choices=[('SSD', 'ssd'), ('HDD', 'hdd')], default='SSD', max_length=10)),
                ('usb', models.BooleanField(default=False)),
                ('sim_card', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('bluetooth', models.BooleanField(default=False)),
                ('hdmi', models.BooleanField(default=False)),
                ('mem_card', models.BooleanField(default=False)),
                ('gps', models.BooleanField(default=False)),
                ('radio', models.BooleanField(default=True)),
                ('Reseau', models.IntegerField(choices=[(2, '2G'), (3, '3G'), (4, '4G'), (5, '5G')], default='4G')),
            ],
            bases=('myapp.device',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=100)),
                ('treated', models.BooleanField(default=False)),
                ('order_datetime', models.DateTimeField(auto_now_add=True)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.basket')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='album',
            field=models.ManyToManyField(to='myapp.image'),
        ),
        migrations.AddField(
            model_name='device',
            name='colors',
            field=models.ManyToManyField(to='myapp.color'),
        ),
        migrations.CreateModel(
            name='DesiredDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb', models.IntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.color')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.device')),
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='devices',
            field=models.ManyToManyField(to='myapp.desireddevice'),
        ),
    ]
