# Generated by Django 4.2.4 on 2023-08-14 11:49

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_device_album_album_device_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='colors',
            field=models.ManyToManyField(blank=True, to='myapp.color'),
        ),
        migrations.AlterField(
            model_name='device',
            name='detail',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='state',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('old', 'Old')], default='new', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='Weight',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='cache_mem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='graphic_card',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='hard_disk',
            field=models.IntegerField(blank=True, choices=[(0, '0 GB'), (64, '64 GB'), (128, '128 GB'), (256, '256 GB'), (512, '512 GB'), (1028, '1028 GB'), (2048, '2048 GB')], default=0),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='os',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='screen_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(null=True, upload_to=myapp.models.upload_to)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.device')),
            ],
        ),
    ]
