# Generated by Django 4.2.4 on 2023-08-14 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_device_colors_alter_device_detail_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
