# Generated by Django 4.2.4 on 2023-08-14 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablet',
            name='hard_disk_type',
        ),
    ]
