# Generated by Django 4.2.4 on 2023-08-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_tablet_hard_disk_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
