# Generated by Django 4.2.4 on 2023-08-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_device_rtnb'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='tags',
            field=models.TextField(null=True),
        ),
    ]
