# Generated by Django 4.2.4 on 2023-08-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_device_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
