# Generated by Django 4.2.4 on 2023-08-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_device_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='datetime',
        ),
        migrations.AddField(
            model_name='device',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
