# Generated by Django 4.2.4 on 2023-08-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_device_datetime_device_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='usb',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='sim_card',
        ),
        migrations.AlterField(
            model_name='laptop',
            name='category',
            field=models.CharField(choices=[('Ultrabook', 'Ultrabook'), ('NetBook', 'Netbook'), ('Classic', 'Classic'), ('Notebook', 'Notebook'), ('1 in 2 laptop', '1 in 2 laptop'), ('Gamer', 'Gamer'), ('Elitebook', 'Elitebook'), ('Probook', 'Probook')], default='Apple', max_length=20),
        ),
    ]
