from rest_framework.routers import DefaultRouter
from . import views
from django.urls import path, include



router = DefaultRouter()
'''
router.register(r'vendor', views.VendorViewSet)
router.register(r'product', views.ProductViewSet)
router.register(r'costumer', views.CostumerViewSet)
router.register(r'order', views.OrderViewSet)
router.register(r'orderitem', views.OrderItemViewSet)
router.register(r'category', views.CategoryViewSet)
router.register(r'address', views.CostumerAddressViewSet)
router.register(r'rating', views.ProductRatingViewSet)
'''
router.register(r'color', views.ColorViewSet)
router.register(r'image', views.ImageViewSet)
router.register(r'device', views.DeviceViewSet)
router.register(r'album', views.AlbumViewSet)
router.register(r'laptop', views.LaptopViewSet)
router.register(r'phone', views.SmartPhoneViewSet)
router.register(r'watch', views.SmartWatchViewSet)
router.register(r'flash', views.FlashDiskViewSet)
router.register(r'bank', views.PowerBankViewSet)
router.register(r'sound', views.SoundDeviceViewSet)
router.register(r'basket', views.BasketViewSet)
router.register(r'laptop', views.LaptopViewSet)
router.register(r'desireddevice', views.DesiredDeviceViewSet)
router.register(r'order', views.OrderViewSet)
router.register(r'feedback', views.FeedbackViewSet)

urlpatterns = [
    # Include the URLs generated by the router
    path('', include(router.urls)),
    path('devicepop/', views.device_popularity_search_view),
    # Add your custom URL pattern
    path('devicedisc/', views.device_discount_search_view),
    path('laptopgen/', views.laptop_general_search_view),
    path('tabletgen/', views.tablet_general_search_view),
    path('smartphonegen/', views.smartphone_general_search_view),
    path('smartwatchgen/', views.smartwatch_general_search_view),
    path('sounddevicegen/', views.sounddevice_general_search_view),
    path('flashdiskgen/', views.flashdisk_general_search_view),
    path('powerbankrange/', views.powerbank_search_range_view),
    path('laptoprange/', views.laptop_search_range_view),
    path('tabletrange/', views.tablet_search_range_view),
    path('smartphonerange/', views.smartphone_search_range_view),
    path('smartwatchrange/', views.smartwatch_search_range_view),
    path('flashdiskrange/', views.flashdisk_search_range_view),
    path('rating/<int:id>/', views.rating),
    path('confirm/<int:id>/', views.confirm_order),

    

]

